baseurl: "https://scovl.github.io"
title: scovl
theme: mycustom
languageCode: en
copyright: Vitor Lobo
disqusShortname: scovl-github-io
pygmentsUseClasses: true
pygmentsCodefences: true
DefaultContentLanguage: pt

languages:
  pt:
    languageName: Portugues
    weight: 1

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    tabWidth: 2
    style: dracula
  goldmark:
    renderer:
      unsafe: true


privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Vitor Lobo
  profile: "https://google.com/+XXX"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  linkedin: "https://linkedin.com/in/vitor-lobo"
  github: "https://github.com/scovl"
  email: lobocode@gmail.com
  opengraph: true
  shareTwitter: true
  shareLinkedIn: true
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  math: true
  navigation:
    help: Help

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Contact
      url: /page/contact/
      weight: 4
    - name: About
      url: /page/about/
      weight: 3
