baseurl: "https://lobocode.github.io"
title: lobocode
theme: mycustom
languageCode: en
copyright: Vitor Lobo
disqusShortname: lobocode-github-io
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Vitor Lobo
  profile: "https://google.com/+XXX"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  linkedin: "https://linkedin.com/in/vitor-lobo"
  github: "https://github.com/lobocode"
  mastodon: "https://bolha.us/@lobocode
  email: lobocode@fedoraproject.org
  opengraph: true
  shareTwitter: true
  shareLinkedIn: true
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Contact
      url: /page/contact/
      weight: 4
    - name: About
      url: /page/about/
      weight: 3
